spring.application.name=lizhi
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/lizhi?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate=DEBUG

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type=trace

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.location= # ????????????????

logging.level.com.example.lizhi=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.multipart=DEBUG
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.add-mappings=true

alipay.app-id=9021000155638628
alipay.private-key=MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCvD33XojSGR3BHYE/N1lA3Zd/Ar7GrR0A+vYxQnWween4XxIA96xEDjbTHRJxyhpoXAahNvs0L/qWoU8q2UpJ+gDl7X/7TmKu93U7FH7E3uD8DdutL78D3av5a4NymjBngE1+EAE5+h2puNgMlqDkB0vqmAF/O61ycUtuLoMKHD99Rzqlq8TQscadHWdG0v/fmKRwP2nmFxvG25D7mUAlxRMFm6wKQ213XlLe2pksOtN7T2GUwTwfidLlJtegb9USNLqbdvIS++PDdqRl/mfhYo719YSvx7WmyY9QEC7w3UMn8LYJsl8SSLkP3ZSiZBjJHnPVi+0/9HtGMxMi9tW0VAgMBAAECggEAHDcv/khrlNUA2NBCLJgFV9h4pvLqfQO/7Bza98dXvNXbavNGBDTWCi+V2qRJXwAo59phiR5eqDdD9gyDWL2YVQFPwn3nca1iyPhZkNYZ1zRAG8vYAuZCwN4i3vztM37TUNVuiLUP8b7bvaXA/hnODmg18/mNd6lhxORp9GhV0jTMUxITc6TIUOVOw8LvY5W9OSacdlAVsahbl4PgpcG8p9Ez0gmxhgwKMYUwGL2EG1CeUpdjuPpB9s+D5w1v+8BgfTtqUJQpDUSfo1JlbmxZ5QeEY6oTcg7SNMOagMoM2GdWrxYqaPo4wbQ7u5yjvpq7iu8bU0A8eaoS82IyKAX7gQKBgQD+PWv0jd2gaDbxNdkAfAdVy8YTH2T123oUOZ4cUU13wF3Cep2A7vnokcyRVxsrx1B41sC3iOiJQeYfgV3l0/ZZs7uq4bo4vO+T7OxDJMrGaf01Wyd0gfniJ09GubHSGIdvJTdnVaK3QIJBEe68vNW5FtU5o5I4fywi4wHiFKMkIQKBgQCwRb5ge3M2LToQqL1/2aqUzOjr4fonvv8DvHHT7CCiqq1fWba5NfI5J6XXdstyb2MyBcaaVEwUTeDEIe8weDc8JRcw6juZQq49XOAz9O2s94K//gGbzjiYJ5kW8FO4Fky1l2temz5lLLaE2d50sz50KFrQBjBc7eDtTQhY1CiqdQKBgCpZxvLs8t82nPhfVO+cuYgUMsGauDGwRsy5sFndPT9WfwfXbwc8R8rzBpWrYe5P/Fq0w1OPbdT3ckMLRL31KhNVOkzD30Z2Sp5kmBKzPUgB/dj2f0MMJ7kBfVY1tqZdyam9FFaVUE6gY1I9j3xHJH75i7lXQxNAM/T3xaeIcoihAoGAbqJHe6zfwdgfAoe18EGAc8YsRqhdZobU7dZfpwAj95SiHh9jtNkr/z1oNFSmGlvY6XOAlCpmWbQLZ25Y/pXlLQWmiZfp8iZMz8y0F0gZyJ7MXI4jGlQTZ0QrLJ+IHBk66hpwVD+hqMSohbdsjNhXUXZmkPvhbOIMc0QPAhmesGUCgYAttQjnJLOByUh/VGDixfhBauftkxAIal8/FbGTbDGKKqH2mkIzmJLeJ+gbWManRTL6UiwzN4bLWNHmv9unfvNA5iSUnYop3g+MkRbe/r1gEXqVnw0EiLCXhW6mPxupCv+Pk3/9FALq6GSs7BnJ8dcZGwiHss6bca+DXKb94aAkDA==
alipay.alipay-public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgkm80yfLiCLT/KldepLYqCelhAJFdly8Nxp3vbuO5SbkBRkTWoGBGhfdfRmfYmwjkg+YGVfHG7WcnvMRsUZBqSEZBUkmCSbsNupBnkpTYk3czwdzEVeCFPKZ6gzS5G7AEXbb5A8jcNHPgOMDgLSQpvOGaqT9aVbEZPmCtfrB6AlmnAP1wTGAv5s4H3UFkFNX91fO0NrwOd7YghAyWptmEP6i9fo2WYom+j5QanCTJmx8XW7MA/tlKEEqrluEFo9v/Kqkot1U66yyC75eP38nsPEHm2YS5P8134EAti/p7PXHN1e46KYGqYumZHPv6UnHeqi8W61vh2YBdgKJXVtYGwIDAQAB
alipay.return-url=http://localhost:8080/otherHtml/payment-success.html
alipay.notify-url=http://localhost:8080/payment/notify
#wxqklv8481@sandbox.com